---
- name: Add Helm apt signing key
  apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

- name: Add Helm Repo
  apt_repository:
    update_cache: yes
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present
    filename: helm-stable-debian.list

- name: Install Helm
  apt:
    name:
      - apt-transport-https
      - helm

